# SPDX-License-Identifier: MIT
"""Pydantic schemas for ERC-8004 validation attestations and verdicts."""

from enum import IntEnum
from typing import List
from pydantic import BaseModel, Field
from shared.schemas.product_schemas import PublicTechnicalAttributes


class ValidationVerdict(IntEnum):
    """Discreet verdict matching AyniAgentRegistry.sol ERC-8004 Validation Registry:
    0 = PASS, 1 = WARN, 2 = FAIL.
    """
    PASS = 0
    WARN = 1
    FAIL = 2


class AttestationResult(BaseModel):
    """Attestation record generated by the Product Verification Agent."""
    verdict: ValidationVerdict
    confidence_score: float = Field(..., ge=0.0, le=1.0)
    flags: List[str] = Field(default_factory=list)
    rationale: str
    request_hash: str = Field(..., description="Bytes32 hex commitment (0x...)")
    validator_agent_id: int = Field(default=42, description="ERC-8004 Validator Agent NFT ID")
    timestamp: int
    version: str = "1.0.0"
    expiry_timestamp: int
    allowed_public_attributes: PublicTechnicalAttributes
